[plugin]
repository = "https://github.com/PYRiTEmonark/PartyListExtras.git"
commit = "396ccf9b9cce8ca33b2e408045c0f969addfcb9a"
owners = ["PYRiTEmonark"]
project_path = "PartyListExtras"
changelog = """- Damage up, Mitigation up and Healing up are now shown in certain fly texts"""
