[plugin]
repository = "https://github.com/PYRiTEmonark/PartyListExtras.git"
commit = "d084a4aab9aa83f84b3969430cf65f99723ec649"
owners = ["PYRiTEmonark"]
project_path = "PartyListExtras"
changelog = """- Conditional statuses implemented
- AST cards now reflect what class they are placed on"""